### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ossuruk3123** [Nick-Vinesmoke/VineShield#4]
It would be better if the console does not open when run. Is there a way to fix this?

**Comment by Nick-Vinesmoke** [comment]
wdm?

**Comment by ossuruk3123** [comment]
> wdm?

I mean the console cmd was not opened when I ran it before crypting, but after crypting cmd opens and then closes, this is a bad thing for me, I want it to be hidden

**Comment by Nick-Vinesmoke** [comment]
It shouldn't open, I think this is an issue with your prog

**Comment by ossuruk3123** [comment]
No, it opens, I am using a stealer's exe, the console does not open before crypting, but when I run it after crypting, a console appears on the screen and then it closes

**Comment by Nick-Vinesmoke** [comment]
I fixed it
